#!/bin/bash
# shellcheck source=script/platform.sh
. "$(dirname "$0")/platform.sh" || exit 1

set -e

SCRIPTSREL=$(dirname "$0")

# Enable Touch ID for sudo
"$SCRIPTSREL/touchid-enable-pam-sudo" --quiet || true

# Set zsh as the default shell
if [ "$SHELL" != "/bin/zsh" ]
then
  chsh -s /bin/zsh "$USER"
fi

"$SCRIPTSREL/../install/mac.sh"
